version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/:/var/lib/mysql/

  web:
    image: leocavalcante/lampiao:1.0
    volumes:
      - ./:/var/www/html/
    ports:
      - "8000:80"
    links:
      - db
