version: "2"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/:/var/lib/mysql/

  web:
    image: leocavalcante/lampiao:<version>
    volumes:
      - ./:/var/www/html/
    ports:
      - "${DOCKER_WEB_PORT}:80"
    links:
      - db
